name: build and release
on:
  push:
    branches:
      - main
    tags:
      - "**"


jobs:
  build_n_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - name: install dependecies
        run: npm install

      - name: load auth_config.json
        run: echo '${{ secrets.AUTH_CONFIG }}' > src/auth_config.json

      - name: buid 
        # skiping fail on warning for now
        run: CI=false npm run build

      - name: archive
        run: tar zvcf build.tgz build

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: none
          pre_release_branches: main
          dry_run: ${{ startsWith(github.ref, 'refs/tags/') }} # dry run if tag and generate output

      - uses: haya14busa/action-cond@v1
        id: condval
        with:
          cond: ${{ startsWith(github.ref, 'refs/tags/') }}
          if_true: "${{ github.ref }}"
          if_false: "${{ steps.tag_version.outputs.new_tag }}"

      - name: Use conditional value
        run: echo "${{ steps.condval.outputs.value }}"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build.tgz
          prerelease: ${{ !startsWith(github.ref, 'refs/tags/') }}
          tag_name: ${{ steps.condval.outputs.value }}