name: Codespell
on: [pull_request]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: codespell
        uses: codespell-project/actions-codespell@v2
        with:
          only_warn: 1
          skip: package-lock.json,*.svg
          ignore_words_list: mappin          
